### ISSUE TITLE
tts-=for soundpad wont install

### ISSUE THREAD

**Issue by cadsett** [medokin/soundpad-text-to-speech#14]
when i try to install it it comes up with a error log

there was an error while installing application. check the setup logs for more info

**Comment by medokin** [comment]
Can you provide the log, or a screenshot? I just tried to install and it works for me.

**Comment by cadsett** [comment]
[SquirrelSetup.log](https://github.com/medokin/soundpad-text-to-speech/files/4671605/SquirrelSetup.log)
here is the log

**Comment by medokin** [comment]
`Access to the path 'C:\Users\Christopher\AppData\Local\TTSApp\app-1.1.1\TTSApp.exe' is denied.`

Maybe try to remove the directory: `C:\Users\Christopher\AppData\Local\TTSApp` and try the installation again.

**Comment by cadsett** [comment]
awesome it worked ! thank you, dont surpose you know anyway to make it work in gtav online? trying to use it in a roleplay server.

**Comment by medokin** [comment]
Not really, sorry. Have fun.
