### ISSUE TITLE
Not working with the newest update from Soundpad 3.3.0

### ISSUE THREAD

**Issue by StaffiiVR** [medokin/soundpad-text-to-speech#15]
It just makes no file, plays nothing, you can type as much as you want and nothing will work

**Comment by medokin** [comment]
I am aware of this problem and in contact with soundpads developer to provider a solution.
You can always downgrade Soundpad until this gets fixed. There is 3.2.x version in Steams Beta channel.

**Comment by medokin** [comment]
I was informed that this is an confirmed issue in Soundpad. The next Soundpad patch should fix it.

**Comment by medokin** [comment]
Soundpad update is available now: https://store.steampowered.com/newshub/app/629520/view/2745457986845286537
