### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by g8orgir1** [medokin/soundpad-text-to-speech#16]
When typing something, the words are not played when entered and the "Play in Soundpad" button stops working.

**Comment by ashenbeauty** [comment]
I have the same issue. This seems to be related to the recent SoundPad 3.3.0 update. I hope Medokin is able to fix this bug, although this tool seems to be somewhat graveyarded.

**Comment by medokin** [comment]
Duplicate of #15

**Comment by medokin** [comment]
@kingcailan It is not graveyarded 🤪 Just because I am not pumping features, does not mean that it is not maintained.

**Comment by ashenbeauty** [comment]
Understood! I tend to assume a project is dead or finished when noone shares bugs, and there are no commits. Sorry for the assumption!
